language: php

php:
  - 7

env:
  - TRAVIS_NODE_VERSION="4.2"

before_script:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - node --version
  - npm install -g npm
  - npm --version
  - npm install
  - composer self-update
  - cp $HOME/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini /tmp
  - phpenv config-rm xdebug.ini # disabling xdebug to speed up composer
  - composer install --prefer-source --no-interaction || true
  - phpenv config-add /tmp/xdebug.ini # enabling xdebug for code coverage
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - php vendor/phpunit/phpunit/phpunit --exclude-group ignore
  - ./node_modules/.bin/jshint  src/app/src/
  - cd src/app
  - ../../node_modules/karma/bin/karma start --single-run

matrix:
  fast_finish: true
