language: php

php:
  - 5.4
  - 5.5
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - npm install

script:
  - php vendor/phpunit/phpunit/phpunit --exclude-group ignore
  - cd src/app
  - ./node_modules/karma/bin/karma start --single-run

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
