language: php

php:
  - 5.4
  - 5.5
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: php vendor/phpunit/phpunit/phpunit --exclude-group ignore

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
